### ISSUE TITLE
遇到两个似乎不影响功能的Exception

### ISSUE THREAD

**Issue by ayanamist** [kooritea/fcmfix#119]
在lsposed的日志里看到的，貌似不影响使用

```
[ 2023-10-14T20:04:29.073     1000:  2032:  2694 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.Class)' on a null object reference
	at com.kooritea.fcmfix.xposed.XposedModule.checkUserDeviceUnlockAndUpdateConfig(XposedModule.java:109)
	at com.kooritea.fcmfix.xposed.XposedModule.targetIsAllow(XposedModule.java:132)
	at com.kooritea.fcmfix.xposed.MiuiLocalNotificationFix$1.afterHookedMethod(MiuiLocalNotificationFix.java:37)
	at E.pZHunNo.oYW.hrXZeoad.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.isAllowLocalNotification(Unknown Source:21)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:5804)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:5786)
	at com.android.server.notification.NotificationManagerService$10.enqueueNotificationWithTag(NotificationManagerService.java:3034)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:584)
	at com.android.server.connectivity.Vpn.updateAlwaysOnNotification(Vpn.java:1812)
	at com.android.server.connectivity.Vpn.updateState(Vpn.java:314)
	at com.android.server.connectivity.Vpn.prepareInternal(Vpn.java:880)
	at com.android.server.connectivity.Vpn.setAlwaysOnPackageInternal(Vpn.java:608)
	at com.android.server.connectivity.Vpn.loadAlwaysOnPackage(Vpn.java:666)
	at com.android.server.connectivity.Vpn.<init>(Vpn.java:292)
	at com.android.server.connectivity.Vpn.<init>(Vpn.java:260)
	at com.android.server.ConnectivityService.onUserStart(ConnectivityService.java:5294)
	at com.android.server.ConnectivityService.access$6600(ConnectivityService.java:266)
	at com.android.server.ConnectivityService$7.onReceive(ConnectivityService.java:5416)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1562)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
[ 2023-10-14T20:06:42.437    10185: 12967: 12967 E/LSPosed-Bridge  ] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedDispatcher;
	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
	at java.lang.reflect.Method.getReturnType(Method.java:148)
	at java.lang.Class.getDeclaredMethods(Class.java:1883)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.lambda$findMethodBestMatch$4(Unknown Source:7)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.e(Unknown Source:0)
	at E.pZHunNo.oYW.hrXZeoad.a.apply(Unknown Source:8)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.callMethod(SourceFile:2)
	at com.kooritea.fcmfix.xposed.ReconnectManagerFix$7.afterHookedMethod(ReconnectManagerFix.java:275)
	at E.pZHunNo.oYW.hrXZeoad.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.onCreate(Unknown Source:11)
	at men.public_onCreate(:com.google.android.gms@233717037@23.37.17 (150400-570218080):1)
	at aehc.onCreate(:com.google.android.gms@233717037@23.37.17 (150400-570218080):4)
	at android.app.Activity.performCreate(Activity.java:8109)
	at android.app.Activity.performCreate(Activity.java:8083)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3474)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3661)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.ClassNotFoundException: android.window.OnBackInvokedDispatcher
	... 31 more
[ 2023-10-14T20:06:55.268    10185: 12967: 12967 E/LSPosed-Bridge  ] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedDispatcher;
	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
	at java.lang.reflect.Method.getReturnType(Method.java:148)
	at java.lang.Class.getDeclaredMethods(Class.java:1883)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.lambda$findMethodBestMatch$4(Unknown Source:7)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.e(Unknown Source:0)
	at E.pZHunNo.oYW.hrXZeoad.a.apply(Unknown Source:8)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at E.pZHunNo.oYW.hrXZeoad.XposedHelpers.callMethod(SourceFile:2)
	at com.kooritea.fcmfix.xposed.ReconnectManagerFix$7.afterHookedMethod(ReconnectManagerFix.java:275)
	at E.pZHunNo.oYW.hrXZeoad.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.onCreate(Unknown Source:11)
	at men.public_onCreate(:com.google.android.gms@233717037@23.37.17 (150400-570218080):1)
	at aehc.onCreate(:com.google.android.gms@233717037@23.37.17 (150400-570218080):4)
	at android.app.Activity.performCreate(Activity.java:8109)
	at android.app.Activity.performCreate(Activity.java:8083)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3474)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3661)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.ClassNotFoundException: android.window.OnBackInvokedDispatcher
	... 31 more
```

**Comment by kooritea** [comment]
上面那个是解除miui对后台应用发通知的限制。
下面那个是gms的，本身hook gms只是为了输出日志，没有什么实际作用
