### ISSUE TITLE
Found a bug about gms for Android 14

### ISSUE THREAD

**Issue by alphime** [kooritea/fcmfix#122]
[ 2023-11-03T09:22:56.189    10278:  3685:  3685 I/LSPosed-Bridge  ]   Loading class com.kooritea.fcmfix.XposedMain
[ 2023-11-03T09:22:56.384    10278:  3685:  3685 I/LSPosed-Bridge  ] [fcmfix] start hook com.google.android.gms
[ 2023-11-03T09:22:56.652    10278:  3685:  3685 E/LSPosed-Bridge  ] java.lang.SecurityException: com.google.android.gms: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at com.kooritea.fcmfix.xposed.XposedModule.initReceiver(XposedModule.java:192)
	at com.kooritea.fcmfix.xposed.XposedModule.callAllOnCanReadConfig(XposedModule.java:74)
	at com.kooritea.fcmfix.xposed.XposedModule.access$000(XposedModule.java:23)
	at com.kooritea.fcmfix.xposed.XposedModule$1.afterHookedMethod(XposedModule.java:59)
	at W.JUYYuZ.U.KCONovDygDt.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at com.google.android.gms.common.app.GmsApplication.attachBaseContextPreMultidex(:com.google.android.gms@234313038@23.43.13 (190400-577232161):42)
	at com.google.android.gms.common.app.GmsApplication.attachBaseContext(:com.google.android.gms@234313038@23.43.13 (190400-577232161):10)
	at android.app.Application.attach(Application.java:346)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1287)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6960)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
	at android.os.Binder.execTransactInternal(Binder.java:1339)
	at android.os.Binder.execTransact(Binder.java:1275)

[ 2023-11-03T09:22:57.010    10278:  3331:  3331 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.USER_UNLOCKED flg=0x50000010 (has extras) } in com.kooritea.fcmfix.xposed.XposedModule$2@bb0095
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.SecurityException: com.google.android.gms: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at com.kooritea.fcmfix.xposed.XposedModule.initReceiver(XposedModule.java:192)
	at com.kooritea.fcmfix.xposed.XposedModule.callAllOnCanReadConfig(XposedModule.java:74)
	at com.kooritea.fcmfix.xposed.XposedModule.access$000(XposedModule.java:23)
	at com.kooritea.fcmfix.xposed.XposedModule$2.onReceive(XposedModule.java:125)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1802)
	... 10 more
[ 2023-11-03T09:22:57.404    10370:  3872:  3872 I/LSPosed-Bridge  ] Loading module com.rosan.xposed.mishare from /data/user/0/com.miui.mishare.connectivity/cache/lspatch/com.rosan.xposed.mishare/2909574351.apk
[ 2023-11-03T09:22:57.432    10370:  3872:  3872 I/LSPosed-Bridge  ]   Loading class com.rosan.xposed.HookInit
[ 2023-11-03T09:22:58.018    10278:  4255:  4255 I/LSPosed-Bridge  ] Loading legacy module com.kooritea.fcmfix from /data/app/~~Ef_oP-geHjlADCpg-O227A==/com.kooritea.fcmfix-ug3LeEIJdDWAhIhWhWP3IA==/base.apk
[ 2023-11-03T09:22:58.252    10278:  4255:  4255 I/LSPosed-Bridge  ]   Loading class com.kooritea.fcmfix.XposedMain
[ 2023-11-03T09:22:58.464    10278:  4255:  4255 I/LSPosed-Bridge  ] [fcmfix] start hook com.google.android.gms
[ 2023-11-03T09:22:58.601    10433:  4448:  4448 I/LSPosed-Bridge  ] Loading legacy module com.kooritea.fcmfix from /data/app/~~Ef_oP-geHjlADCpg-O227A==/com.kooritea.fcmfix-ug3LeEIJdDWAhIhWhWP3IA==/base.apk
[ 2023-11-03T09:22:58.645    10278:  4255:  4255 E/LSPosed-Bridge  ] java.lang.SecurityException: com.google.android.gms: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at com.kooritea.fcmfix.xposed.XposedModule.initReceiver(XposedModule.java:192)
	at com.kooritea.fcmfix.xposed.XposedModule.callAllOnCanReadConfig(XposedModule.java:74)
	at com.kooritea.fcmfix.xposed.XposedModule.access$000(XposedModule.java:23)
	at com.kooritea.fcmfix.xposed.XposedModule$1.afterHookedMethod(XposedModule.java:59)
	at W.JUYYuZ.U.KCONovDygDt.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at com.google.android.gms.common.app.GmsApplication.attachBaseContextPreMultidex(:com.google.android.gms@234313038@23.43.13 (190400-577232161):42)
	at com.google.android.gms.common.app.GmsApplication.attachBaseContext(:com.google.android.gms@234313038@23.43.13 (190400-577232161):10)
	at android.app.Application.attach(Application.java:346)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1287)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6960)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
	at android.os.Binder.execTransactInternal(Binder.java:1339)
	at android.os.Binder.execTransact(Binder.java:1275)
![Screenshot_20231103-092855](https://github.com/kooritea/fcmfix/assets/109449075/3ceb3b82-4e4f-4335-8304-09bc75381312)

**Comment by kooritea** [comment]
fix https://github.com/kooritea/fcmfix/commit/76aae7f6452d40a3f317409f8e708ba6e2ccb9c2
