### ISSUE TITLE
“阻止应用停止时自动清除通知“功能报错

### ISSUE THREAD

**Issue by RichardLuo0** [kooritea/fcmfix#139]
android 14
只要在fcmfix里选中的应用被强行停止，fcmfix就会报这个错

```
[ 2024-03-15T16:32:59.649     1000:  1463:  1463 E/LSPosed-Bridge  ] java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
	at com.kooritea.fcmfix.xposed.KeepNotification$1.beforeHookedMethod(KeepNotification.java:41)
	at rZG.HtPnRxBmy.RDjplQIQ.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:179)
	at LSPHooker_.cancelAllNotificationsInt(Unknown Source:58)
	at com.android.server.notification.NotificationManagerService$5.onReceive(NotificationManagerService.java:1808)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1811)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.android.server.SystemServer.run(SystemServer.java:988)
	at com.android.server.SystemServer.main(SystemServer.java:674)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:949)
```

**Comment by kooritea** [comment]
这个是在应用被结束时保留通知的，看来是在14要重新适配了

**Comment by RichardLuo0** [comment]
> 这个是在应用被结束时保留通知的，看来是在14要重新适配了

请问什么时候能修复？主要还挺需要这个功能的。

**Comment by kooritea** [comment]
https://github.com/kooritea/fcmfix/releases/tag/20240412-7b742f8

试试这个

**Comment by RichardLuo0** [comment]
报错确实不报了 但是不确定功能是不是正常
