### ISSUE TITLE
无法正确调用targetIsAllow方法

### ISSUE THREAD

**Issue by MinaMichita** [kooritea/fcmfix#21]
设备：K30 5G/K40
系统：MIUI 21.8.18
在调用targetIsAllow方法时报以下错误：

`2021-08-25 14:14:05.568 1453-1570/? W/Binder: Outgoing transactions from this process must be FLAG_ONEWAY
    java.lang.Throwable
        at android.os.BinderProxy.transact(BinderProxy.java:559)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:470)
        at android.content.ContentResolver.query(ContentResolver.java:1197)
        at android.content.ContentResolver.query(ContentResolver.java:1128)
        at android.content.ContentResolver.query(ContentResolver.java:1084)
        at com.kooritea.fcmfix.util.ContentProviderHelper.getStringSet(ContentProviderHelper.java:68)
        at com.kooritea.fcmfix.xposed.XposedModule.onUpdateConfig(XposedModule.java:104)
        at com.kooritea.fcmfix.xposed.XposedModule.checkUserDeviceUnlockAndUpdateConfig(XposedModule.java:63)
        at com.kooritea.fcmfix.xposed.XposedModule.targetIsAllow(XposedModule.java:88)
        at com.kooritea.fcmfix.xposed.MiuiLocalNotificationFix$1.afterHookedMethod(MiuiLocalNotificationFix.java:30)
        at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
        at LspHooker_.isAllowLocalNotification(Unknown Source:21)
        at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:5791)
        at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:5773)
        at com.android.server.notification.NotificationManagerService$11.enqueueNotification(NotificationManagerService.java:5657)
        at com.android.server.am.ServiceRecord$1.run(ServiceRecord.java:961)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:45)`

**Comment by kooritea** [comment]
给fcmfix自启动权限试试看

**Comment by kooritea** [comment]
或者试试0.3.3版本，不知道是不是改了获取context的问题..?

**Comment by MinaMichita** [comment]
试了一下在0.10版本上getStringSet就有问题了，在MIUI EU上也会出现同样的错误。

**Comment by kooritea** [comment]
0.1.0好像还在用sharedpreferences来着

**Comment by MinaMichita** [comment]
感觉有点奇奇怪怪的==。这个问题在0.3.3也会出现所以应该跟context的获取方式没有关系。既然xposed模块能够读取文件是否可以试着换一个方案，直接读取/data/user/0/com.kooritea.fcmfix/shared_prefs/config.xml的内容？

**Comment by kooritea** [comment]
貌似高版本系统只有安卓作用域能读取到其他应用的SharedPreferences，所以才改用ContentProvider的(虽然现在暂时不需要在勾在其他应用的模块上读取config.xml

**Comment by MinaMichita** [comment]
然后还有一点很诡异的是，在开机一段时间后（具体时间不太清楚）就不会出现这个错误了。只在刚开完机的一段时间内会出现这个错误。

**Comment by kooritea** [comment]
刚开机可能是有什么魔法导致fcmfix拉不起来吧，这个方法第一次调用会先拉起本体读白名单

**Comment by MinaMichita** [comment]
以及还有个很诡异的情况，我自己多写了几个类，有的类能正常读取有的类不能正常读取。是否能考虑更换一下机制？

**Comment by kooritea** [comment]
暂时找不到更好的方案。。

**Comment by MinaMichita** [comment]
因为有的类能读取有些类不能，我这边的做法是把所有的hook都放到同一个类下然后公用一个allowlist，测试后是正常了，开机解锁后马上就能读到列表。可以考虑一下改写xposed部分的代码，虽然将全部东西放进一个类下代码会冗长一些但是暂时想不到其它解决办法了。。。
