### ISSUE TITLE
启动时hook 系统通知出错

### ISSUE THREAD

**Issue by Oosl** [kooritea/fcmfix#37]
系统是：ColorOS 12，安卓12
play服务版本：21.48.15

[ 2022-01-15T13:44:06.508     1000:  1575:  1575 I/LSPosed-Bridge  ] [fcmfix] start hook com.android.server.notification.NotificationManagerServiceInjector
[ 2022-01-15T13:44:06.508     1000:  1575:  1575 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.notification.NotificationManagerServiceInjector
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at com.kooritea.fcmfix.xposed.MiuiLocalNotificationFix.startHook(MiuiLocalNotificationFix.java:17)
	at com.kooritea.fcmfix.xposed.MiuiLocalNotificationFix.<init>(MiuiLocalNotificationFix.java:13)
	at com.kooritea.fcmfix.XposedMain.handleLoadPackage(XposedMain.java:26)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at o.beforeHookedMethod(Unknown Source:3)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:927)
	at com.android.server.SystemServer.main(SystemServer.java:632)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
Caused by: java.lang.ClassNotFoundException: com.android.server.notification.NotificationManagerServiceInjector
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at m.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.android.server.notification.NotificationManagerServiceInjector
	... 18 more

**Comment by kooritea** [comment]
fcmfix有没有更新到最新版

**Comment by Oosl** [comment]
有，fcm已是最新版0.4.3

**Comment by kooritea** [comment]
我好像知道问题了。。 有空改

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/fcmfix/files/7893850/app-release.zip)
试一下这个？

**Comment by Oosl** [comment]
> [app-release.zip](https://github.com/kooritea/fcmfix/files/7893850/app-release.zip)
> 试一下这个？

[ 2022-01-19T11:38:17.566     1000:  1853:  1853 I/LSPosed-Bridge  ] [fcmfix] start hook com.android.server.am.ActivityManagerService
[ 2022-01-19T11:38:17.569     1000:  1853:  1853 I/LSPosed-Bridge  ] [fcmfix] start hook com.android.server.notification.NotificationManagerServiceInjector
[ 2022-01-19T11:38:17.570     1000:  1853:  1853 I/LSPosed-Bridge  ] [fcmfix] Not found isAllowLocalNotification in com.android.server.notification.NotificationManagerServiceInjector
[ 2022-01-19T11:38:17.570     1000:  1853:  1853 I/LSPosed-Bridge  ] [fcmfix] com.android.server.am.BroadcastQueueInjector.checkApplicationAutoStart
[ 2022-01-19T11:38:17.570     1000:  1853:  1853 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.am.BroadcastQueueInjector
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at com.kooritea.fcmfix.xposed.AutoStartFix.startHook(AutoStartFix.java:19)
	at com.kooritea.fcmfix.xposed.AutoStartFix.<init>(AutoStartFix.java:15)
	at com.kooritea.fcmfix.XposedMain.handleLoadPackage(XposedMain.java:29)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at o.beforeHookedMethod(Unknown Source:3)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:927)
	at com.android.server.SystemServer.main(SystemServer.java:632)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
Caused by: java.lang.ClassNotFoundException: com.android.server.am.BroadcastQueueInjector
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at m.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.android.server.am.BroadcastQueueInjector
	... 18 more

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/fcmfix/files/7894389/app-release.zip)
再试试这个，这两个异常都是针对miui的功能没处理其他系统导致的

**Comment by Oosl** [comment]
嗯，现在看起来异常都被catch了，没有直接打印报错信息了。

**Comment by kooritea** [comment]
因为不是miui系统，正常

**Comment by Oosl** [comment]
好的，反正没COS什么事就是了，哈哈。谢啦
